#include <windows.h>
#include <imm.h>
#include <commdlg.h>
#include <dwmapi.h>
#include <oleidl.h>
#include <shobjidl.h>
#include <shlobj.h>
#include <knownfolders.h>
#include <uiautomationcore.h>
#include <uiautomationcoreapi.h>
#include <stddef.h>
#include <stdio.h>
int main(void) {
    _Static_assert(sizeof(WNDCLASSEXW) == 80, "WNDCLASSEXW");
    printf("WNDCLASSEXW %zu\n", sizeof(WNDCLASSEXW));
    _Static_assert(sizeof(POINT) == 8, "POINT");
    printf("POINT %zu\n", sizeof(POINT));
    _Static_assert(sizeof(MSG) == 48, "MSG");
    printf("MSG %zu\n", sizeof(MSG));
    _Static_assert(sizeof(RECT) == 16, "RECT");
    printf("RECT %zu\n", sizeof(RECT));
    _Static_assert(sizeof(PAINTSTRUCT) == 72, "PAINTSTRUCT");
    printf("PAINTSTRUCT %zu\n", sizeof(PAINTSTRUCT));
    _Static_assert(sizeof(MINMAXINFO) == 40, "MINMAXINFO");
    printf("MINMAXINFO %zu\n", sizeof(MINMAXINFO));
    _Static_assert(sizeof(TRACKMOUSEEVENT) == 24, "TRACKMOUSEEVENT");
    printf("TRACKMOUSEEVENT %zu\n", sizeof(TRACKMOUSEEVENT));
    _Static_assert(sizeof(CREATESTRUCTW) == 80, "CREATESTRUCTW");
    printf("CREATESTRUCTW %zu\n", sizeof(CREATESTRUCTW));
    _Static_assert(sizeof(BITMAPINFOHEADER) == 40, "BITMAPINFOHEADER");
    printf("BITMAPINFOHEADER %zu\n", sizeof(BITMAPINFOHEADER));
    _Static_assert(sizeof(RGBQUAD) == 4, "RGBQUAD");
    printf("RGBQUAD %zu\n", sizeof(RGBQUAD));
    _Static_assert(sizeof(BITMAPINFO) == 44, "BITMAPINFO");
    printf("BITMAPINFO %zu\n", sizeof(BITMAPINFO));
    _Static_assert(sizeof(BLENDFUNCTION) == 4, "BLENDFUNCTION");
    printf("BLENDFUNCTION %zu\n", sizeof(BLENDFUNCTION));
    _Static_assert(sizeof(WINDOWPLACEMENT) == 44, "WINDOWPLACEMENT");
    printf("WINDOWPLACEMENT %zu\n", sizeof(WINDOWPLACEMENT));
    _Static_assert(sizeof(LOGFONTW) == 92, "LOGFONTW");
    printf("LOGFONTW %zu\n", sizeof(LOGFONTW));
    _Static_assert(sizeof(NONCLIENTMETRICSW) == 504, "NONCLIENTMETRICSW");
    printf("NONCLIENTMETRICSW %zu\n", sizeof(NONCLIENTMETRICSW));
    _Static_assert(sizeof(HIGHCONTRASTW) == 16, "HIGHCONTRASTW");
    printf("HIGHCONTRASTW %zu\n", sizeof(HIGHCONTRASTW));
    _Static_assert(sizeof(OPENFILENAMEW) == 152, "OPENFILENAMEW");
    printf("OPENFILENAMEW %zu\n", sizeof(OPENFILENAMEW));
    _Static_assert(sizeof(FILETIME) == 8, "FILETIME");
    printf("FILETIME %zu\n", sizeof(FILETIME));
    _Static_assert(sizeof(WIN32_FIND_DATAW) == 592, "WIN32_FIND_DATAW");
    printf("WIN32_FIND_DATAW %zu\n", sizeof(WIN32_FIND_DATAW));
    _Static_assert(sizeof(COMPOSITIONFORM) == 28, "COMPOSITIONFORM");
    printf("COMPOSITIONFORM %zu\n", sizeof(COMPOSITIONFORM));
    _Static_assert(sizeof(CANDIDATEFORM) == 32, "CANDIDATEFORM");
    printf("CANDIDATEFORM %zu\n", sizeof(CANDIDATEFORM));
    _Static_assert(sizeof(GUID) == 16, "GUID");
    printf("GUID %zu\n", sizeof(GUID));
    _Static_assert(sizeof(NOTIFYICONDATAW) == 976, "NOTIFYICONDATAW");
    printf("NOTIFYICONDATAW %zu\n", sizeof(NOTIFYICONDATAW));
    _Static_assert(sizeof(FORMATETC) == 32, "FORMATETC");
    printf("FORMATETC %zu\n", sizeof(FORMATETC));
    _Static_assert(sizeof(STGMEDIUM) == 24, "STGMEDIUM");
    printf("STGMEDIUM %zu\n", sizeof(STGMEDIUM));
    _Static_assert(sizeof(VARIANT) == 24, "VARIANT");
    printf("VARIANT %zu\n", sizeof(VARIANT));
    _Static_assert(sizeof(SAFEARRAYBOUND) == 8, "SAFEARRAYBOUND");
    printf("SAFEARRAYBOUND %zu\n", sizeof(SAFEARRAYBOUND));
    _Static_assert(sizeof(SAFEARRAY) == 32, "SAFEARRAY");
    printf("SAFEARRAY %zu\n", sizeof(SAFEARRAY));
    _Static_assert(sizeof(COMDLG_FILTERSPEC) == 16, "COMDLG_FILTERSPEC");
    printf("COMDLG_FILTERSPEC %zu\n", sizeof(COMDLG_FILTERSPEC));
    _Static_assert(sizeof(DISPPARAMS) == 24, "DISPPARAMS");
    printf("DISPPARAMS %zu\n", sizeof(DISPPARAMS));
    _Static_assert(sizeof(EXCEPINFO) == 64, "EXCEPINFO");
    printf("EXCEPINFO %zu\n", sizeof(EXCEPINFO));
    _Static_assert(sizeof(INPUT) == 40, "INPUT");
    printf("INPUT %zu\n", sizeof(INPUT));
    _Static_assert(sizeof(MARGINS) == 16, "MARGINS");
    printf("MARGINS %zu\n", sizeof(MARGINS));
    _Static_assert(sizeof(MONITORINFO) == 40, "MONITORINFO");
    printf("MONITORINFO %zu\n", sizeof(MONITORINFO));
    _Static_assert(sizeof(IUnknownVtbl) == 24, "IUnknownVtbl");
    printf("IUnknownVtbl %zu\n", sizeof(IUnknownVtbl));
    _Static_assert(sizeof(IUnknown) == 8, "IUnknown");
    printf("IUnknown %zu\n", sizeof(IUnknown));
    _Static_assert(sizeof(IDropTargetVtbl) == 56, "IDropTargetVtbl");
    printf("IDropTargetVtbl %zu\n", sizeof(IDropTargetVtbl));
    _Static_assert(sizeof(IDropTarget) == 8, "IDropTarget");
    printf("IDropTarget %zu\n", sizeof(IDropTarget));
    _Static_assert(sizeof(IDataObjectVtbl) == 96, "IDataObjectVtbl");
    printf("IDataObjectVtbl %zu\n", sizeof(IDataObjectVtbl));
    _Static_assert(sizeof(IDataObject) == 8, "IDataObject");
    printf("IDataObject %zu\n", sizeof(IDataObject));
    _Static_assert(sizeof(IDropSourceVtbl) == 40, "IDropSourceVtbl");
    printf("IDropSourceVtbl %zu\n", sizeof(IDropSourceVtbl));
    _Static_assert(sizeof(IDropSource) == 8, "IDropSource");
    printf("IDropSource %zu\n", sizeof(IDropSource));
    _Static_assert(sizeof(IFileOpenDialogVtbl) == 232, "IFileOpenDialogVtbl");
    printf("IFileOpenDialogVtbl %zu\n", sizeof(IFileOpenDialogVtbl));
    _Static_assert(sizeof(IFileOpenDialog) == 8, "IFileOpenDialog");
    printf("IFileOpenDialog %zu\n", sizeof(IFileOpenDialog));
    _Static_assert(sizeof(IFileSaveDialogVtbl) == 256, "IFileSaveDialogVtbl");
    printf("IFileSaveDialogVtbl %zu\n", sizeof(IFileSaveDialogVtbl));
    _Static_assert(sizeof(IFileSaveDialog) == 8, "IFileSaveDialog");
    printf("IFileSaveDialog %zu\n", sizeof(IFileSaveDialog));
    _Static_assert(sizeof(IShellItemVtbl) == 64, "IShellItemVtbl");
    printf("IShellItemVtbl %zu\n", sizeof(IShellItemVtbl));
    _Static_assert(sizeof(IShellItem) == 8, "IShellItem");
    printf("IShellItem %zu\n", sizeof(IShellItem));
    _Static_assert(sizeof(IShellItemArrayVtbl) == 80, "IShellItemArrayVtbl");
    printf("IShellItemArrayVtbl %zu\n", sizeof(IShellItemArrayVtbl));
    _Static_assert(sizeof(IShellItemArray) == 8, "IShellItemArray");
    printf("IShellItemArray %zu\n", sizeof(IShellItemArray));
    _Static_assert(sizeof(IRawElementProviderSimpleVtbl) == 56, "IRawElementProviderSimpleVtbl");
    printf("IRawElementProviderSimpleVtbl %zu\n", sizeof(IRawElementProviderSimpleVtbl));
    _Static_assert(sizeof(IRawElementProviderSimple) == 8, "IRawElementProviderSimple");
    printf("IRawElementProviderSimple %zu\n", sizeof(IRawElementProviderSimple));
    _Static_assert(sizeof(IRawElementProviderFragmentVtbl) == 72, "IRawElementProviderFragmentVtbl");
    printf("IRawElementProviderFragmentVtbl %zu\n", sizeof(IRawElementProviderFragmentVtbl));
    _Static_assert(sizeof(IRawElementProviderFragment) == 8, "IRawElementProviderFragment");
    printf("IRawElementProviderFragment %zu\n", sizeof(IRawElementProviderFragment));
    _Static_assert(sizeof(IRawElementProviderFragmentRootVtbl) == 40, "IRawElementProviderFragmentRootVtbl");
    printf("IRawElementProviderFragmentRootVtbl %zu\n", sizeof(IRawElementProviderFragmentRootVtbl));
    _Static_assert(sizeof(IRawElementProviderFragmentRoot) == 8, "IRawElementProviderFragmentRoot");
    printf("IRawElementProviderFragmentRoot %zu\n", sizeof(IRawElementProviderFragmentRoot));
    _Static_assert(sizeof(IInvokeProviderVtbl) == 32, "IInvokeProviderVtbl");
    printf("IInvokeProviderVtbl %zu\n", sizeof(IInvokeProviderVtbl));
    _Static_assert(sizeof(IInvokeProvider) == 8, "IInvokeProvider");
    printf("IInvokeProvider %zu\n", sizeof(IInvokeProvider));
    _Static_assert(sizeof(IToggleProviderVtbl) == 40, "IToggleProviderVtbl");
    printf("IToggleProviderVtbl %zu\n", sizeof(IToggleProviderVtbl));
    _Static_assert(sizeof(IToggleProvider) == 8, "IToggleProvider");
    printf("IToggleProvider %zu\n", sizeof(IToggleProvider));
    _Static_assert(sizeof(IValueProviderVtbl) == 48, "IValueProviderVtbl");
    printf("IValueProviderVtbl %zu\n", sizeof(IValueProviderVtbl));
    _Static_assert(sizeof(IValueProvider) == 8, "IValueProvider");
    printf("IValueProvider %zu\n", sizeof(IValueProvider));
    _Static_assert(sizeof(IRangeValueProviderVtbl) == 80, "IRangeValueProviderVtbl");
    printf("IRangeValueProviderVtbl %zu\n", sizeof(IRangeValueProviderVtbl));
    _Static_assert(sizeof(IRangeValueProvider) == 8, "IRangeValueProvider");
    printf("IRangeValueProvider %zu\n", sizeof(IRangeValueProvider));
    _Static_assert(sizeof(ITextProviderVtbl) == 72, "ITextProviderVtbl");
    printf("ITextProviderVtbl %zu\n", sizeof(ITextProviderVtbl));
    _Static_assert(sizeof(ITextProvider) == 8, "ITextProvider");
    printf("ITextProvider %zu\n", sizeof(ITextProvider));
    _Static_assert(sizeof(ITextRangeProviderVtbl) == 168, "ITextRangeProviderVtbl");
    printf("ITextRangeProviderVtbl %zu\n", sizeof(ITextRangeProviderVtbl));
    _Static_assert(sizeof(ITextRangeProvider) == 8, "ITextRangeProvider");
    printf("ITextRangeProvider %zu\n", sizeof(ITextRangeProvider));
    _Static_assert(sizeof(ISelectionProviderVtbl) == 48, "ISelectionProviderVtbl");
    printf("ISelectionProviderVtbl %zu\n", sizeof(ISelectionProviderVtbl));
    _Static_assert(sizeof(ISelectionProvider) == 8, "ISelectionProvider");
    printf("ISelectionProvider %zu\n", sizeof(ISelectionProvider));
    _Static_assert(sizeof(ISelectionItemProviderVtbl) == 64, "ISelectionItemProviderVtbl");
    printf("ISelectionItemProviderVtbl %zu\n", sizeof(ISelectionItemProviderVtbl));
    _Static_assert(sizeof(ISelectionItemProvider) == 8, "ISelectionItemProvider");
    printf("ISelectionItemProvider %zu\n", sizeof(ISelectionItemProvider));
    _Static_assert(sizeof(IExpandCollapseProviderVtbl) == 48, "IExpandCollapseProviderVtbl");
    printf("IExpandCollapseProviderVtbl %zu\n", sizeof(IExpandCollapseProviderVtbl));
    _Static_assert(sizeof(IExpandCollapseProvider) == 8, "IExpandCollapseProvider");
    printf("IExpandCollapseProvider %zu\n", sizeof(IExpandCollapseProvider));
    _Static_assert(sizeof(IScrollProviderVtbl) == 88, "IScrollProviderVtbl");
    printf("IScrollProviderVtbl %zu\n", sizeof(IScrollProviderVtbl));
    _Static_assert(sizeof(IScrollProvider) == 8, "IScrollProvider");
    printf("IScrollProvider %zu\n", sizeof(IScrollProvider));
    _Static_assert(sizeof(IScrollItemProviderVtbl) == 32, "IScrollItemProviderVtbl");
    printf("IScrollItemProviderVtbl %zu\n", sizeof(IScrollItemProviderVtbl));
    _Static_assert(sizeof(IScrollItemProvider) == 8, "IScrollItemProvider");
    printf("IScrollItemProvider %zu\n", sizeof(IScrollItemProvider));
    _Static_assert(sizeof(IGridProviderVtbl) == 48, "IGridProviderVtbl");
    printf("IGridProviderVtbl %zu\n", sizeof(IGridProviderVtbl));
    _Static_assert(sizeof(IGridProvider) == 8, "IGridProvider");
    printf("IGridProvider %zu\n", sizeof(IGridProvider));
    _Static_assert(sizeof(IGridItemProviderVtbl) == 64, "IGridItemProviderVtbl");
    printf("IGridItemProviderVtbl %zu\n", sizeof(IGridItemProviderVtbl));
    _Static_assert(sizeof(IGridItemProvider) == 8, "IGridItemProvider");
    printf("IGridItemProvider %zu\n", sizeof(IGridItemProvider));
    _Static_assert(sizeof(ITableProviderVtbl) == 48, "ITableProviderVtbl");
    printf("ITableProviderVtbl %zu\n", sizeof(ITableProviderVtbl));
    _Static_assert(sizeof(ITableProvider) == 8, "ITableProvider");
    printf("ITableProvider %zu\n", sizeof(ITableProvider));
    _Static_assert(sizeof(ITableItemProviderVtbl) == 40, "ITableItemProviderVtbl");
    printf("ITableItemProviderVtbl %zu\n", sizeof(ITableItemProviderVtbl));
    _Static_assert(sizeof(ITableItemProvider) == 8, "ITableItemProvider");
    printf("ITableItemProvider %zu\n", sizeof(ITableItemProvider));
    _Static_assert(offsetof(WNDCLASSEXW, cbSize) == 0, "WNDCLASSEXW.cbSize");
    _Static_assert(offsetof(WNDCLASSEXW, style) == 4, "WNDCLASSEXW.style");
    _Static_assert(offsetof(WNDCLASSEXW, lpfnWndProc) == 8, "WNDCLASSEXW.lpfnWndProc");
    _Static_assert(offsetof(WNDCLASSEXW, cbClsExtra) == 16, "WNDCLASSEXW.cbClsExtra");
    _Static_assert(offsetof(WNDCLASSEXW, cbWndExtra) == 20, "WNDCLASSEXW.cbWndExtra");
    _Static_assert(offsetof(WNDCLASSEXW, hInstance) == 24, "WNDCLASSEXW.hInstance");
    _Static_assert(offsetof(WNDCLASSEXW, hIcon) == 32, "WNDCLASSEXW.hIcon");
    _Static_assert(offsetof(WNDCLASSEXW, hCursor) == 40, "WNDCLASSEXW.hCursor");
    _Static_assert(offsetof(WNDCLASSEXW, hbrBackground) == 48, "WNDCLASSEXW.hbrBackground");
    _Static_assert(offsetof(WNDCLASSEXW, lpszMenuName) == 56, "WNDCLASSEXW.lpszMenuName");
    _Static_assert(offsetof(WNDCLASSEXW, lpszClassName) == 64, "WNDCLASSEXW.lpszClassName");
    _Static_assert(offsetof(WNDCLASSEXW, hIconSm) == 72, "WNDCLASSEXW.hIconSm");
    _Static_assert(offsetof(MSG, hwnd) == 0, "MSG.hwnd");
    _Static_assert(offsetof(MSG, message) == 8, "MSG.message");
    _Static_assert(offsetof(MSG, wParam) == 16, "MSG.wParam");
    _Static_assert(offsetof(MSG, lParam) == 24, "MSG.lParam");
    _Static_assert(offsetof(MSG, time) == 32, "MSG.time");
    _Static_assert(offsetof(POINT, x) == 0, "POINT.x");
    _Static_assert(offsetof(POINT, y) == 4, "POINT.y");
    _Static_assert(offsetof(MSG, pt) == 36, "MSG.pt");
    _Static_assert(offsetof(RECT, left) == 0, "RECT.left");
    _Static_assert(offsetof(RECT, top) == 4, "RECT.top");
    _Static_assert(offsetof(RECT, right) == 8, "RECT.right");
    _Static_assert(offsetof(RECT, bottom) == 12, "RECT.bottom");
    _Static_assert(offsetof(PAINTSTRUCT, hdc) == 0, "PAINTSTRUCT.hdc");
    _Static_assert(offsetof(PAINTSTRUCT, fErase) == 8, "PAINTSTRUCT.fErase");
    _Static_assert(offsetof(PAINTSTRUCT, rcPaint) == 12, "PAINTSTRUCT.rcPaint");
    _Static_assert(offsetof(PAINTSTRUCT, fRestore) == 28, "PAINTSTRUCT.fRestore");
    _Static_assert(offsetof(PAINTSTRUCT, fIncUpdate) == 32, "PAINTSTRUCT.fIncUpdate");
    _Static_assert(offsetof(PAINTSTRUCT, rgbReserved) == 36, "PAINTSTRUCT.rgbReserved");
    _Static_assert(offsetof(MINMAXINFO, ptReserved) == 0, "MINMAXINFO.ptReserved");
    _Static_assert(offsetof(MINMAXINFO, ptMaxSize) == 8, "MINMAXINFO.ptMaxSize");
    _Static_assert(offsetof(MINMAXINFO, ptMaxPosition) == 16, "MINMAXINFO.ptMaxPosition");
    _Static_assert(offsetof(MINMAXINFO, ptMinTrackSize) == 24, "MINMAXINFO.ptMinTrackSize");
    _Static_assert(offsetof(MINMAXINFO, ptMaxTrackSize) == 32, "MINMAXINFO.ptMaxTrackSize");
    _Static_assert(offsetof(TRACKMOUSEEVENT, cbSize) == 0, "TRACKMOUSEEVENT.cbSize");
    _Static_assert(offsetof(TRACKMOUSEEVENT, dwFlags) == 4, "TRACKMOUSEEVENT.dwFlags");
    _Static_assert(offsetof(TRACKMOUSEEVENT, hwndTrack) == 8, "TRACKMOUSEEVENT.hwndTrack");
    _Static_assert(offsetof(TRACKMOUSEEVENT, dwHoverTime) == 16, "TRACKMOUSEEVENT.dwHoverTime");
    _Static_assert(offsetof(CREATESTRUCTW, lpCreateParams) == 0, "CREATESTRUCTW.lpCreateParams");
    _Static_assert(offsetof(CREATESTRUCTW, hInstance) == 8, "CREATESTRUCTW.hInstance");
    _Static_assert(offsetof(CREATESTRUCTW, hMenu) == 16, "CREATESTRUCTW.hMenu");
    _Static_assert(offsetof(CREATESTRUCTW, hwndParent) == 24, "CREATESTRUCTW.hwndParent");
    _Static_assert(offsetof(CREATESTRUCTW, cy) == 32, "CREATESTRUCTW.cy");
    _Static_assert(offsetof(CREATESTRUCTW, cx) == 36, "CREATESTRUCTW.cx");
    _Static_assert(offsetof(CREATESTRUCTW, y) == 40, "CREATESTRUCTW.y");
    _Static_assert(offsetof(CREATESTRUCTW, x) == 44, "CREATESTRUCTW.x");
    _Static_assert(offsetof(CREATESTRUCTW, style) == 48, "CREATESTRUCTW.style");
    _Static_assert(offsetof(CREATESTRUCTW, lpszName) == 56, "CREATESTRUCTW.lpszName");
    _Static_assert(offsetof(CREATESTRUCTW, lpszClass) == 64, "CREATESTRUCTW.lpszClass");
    _Static_assert(offsetof(CREATESTRUCTW, dwExStyle) == 72, "CREATESTRUCTW.dwExStyle");
    _Static_assert(offsetof(BITMAPINFOHEADER, biSize) == 0, "BITMAPINFOHEADER.biSize");
    _Static_assert(offsetof(BITMAPINFOHEADER, biWidth) == 4, "BITMAPINFOHEADER.biWidth");
    _Static_assert(offsetof(BITMAPINFOHEADER, biHeight) == 8, "BITMAPINFOHEADER.biHeight");
    _Static_assert(offsetof(BITMAPINFOHEADER, biPlanes) == 12, "BITMAPINFOHEADER.biPlanes");
    _Static_assert(offsetof(BITMAPINFOHEADER, biBitCount) == 14, "BITMAPINFOHEADER.biBitCount");
    _Static_assert(offsetof(BITMAPINFOHEADER, biCompression) == 16, "BITMAPINFOHEADER.biCompression");
    _Static_assert(offsetof(BITMAPINFOHEADER, biSizeImage) == 20, "BITMAPINFOHEADER.biSizeImage");
    _Static_assert(offsetof(BITMAPINFOHEADER, biXPelsPerMeter) == 24, "BITMAPINFOHEADER.biXPelsPerMeter");
    _Static_assert(offsetof(BITMAPINFOHEADER, biYPelsPerMeter) == 28, "BITMAPINFOHEADER.biYPelsPerMeter");
    _Static_assert(offsetof(BITMAPINFOHEADER, biClrUsed) == 32, "BITMAPINFOHEADER.biClrUsed");
    _Static_assert(offsetof(BITMAPINFOHEADER, biClrImportant) == 36, "BITMAPINFOHEADER.biClrImportant");
    _Static_assert(offsetof(BITMAPINFO, bmiHeader) == 0, "BITMAPINFO.bmiHeader");
    _Static_assert(offsetof(RGBQUAD, rgbBlue) == 0, "RGBQUAD.rgbBlue");
    _Static_assert(offsetof(RGBQUAD, rgbGreen) == 1, "RGBQUAD.rgbGreen");
    _Static_assert(offsetof(RGBQUAD, rgbRed) == 2, "RGBQUAD.rgbRed");
    _Static_assert(offsetof(RGBQUAD, rgbReserved) == 3, "RGBQUAD.rgbReserved");
    _Static_assert(offsetof(BITMAPINFO, bmiColors) == 40, "BITMAPINFO.bmiColors");
    _Static_assert(offsetof(BLENDFUNCTION, BlendOp) == 0, "BLENDFUNCTION.BlendOp");
    _Static_assert(offsetof(BLENDFUNCTION, BlendFlags) == 1, "BLENDFUNCTION.BlendFlags");
    _Static_assert(offsetof(BLENDFUNCTION, SourceConstantAlpha) == 2, "BLENDFUNCTION.SourceConstantAlpha");
    _Static_assert(offsetof(BLENDFUNCTION, AlphaFormat) == 3, "BLENDFUNCTION.AlphaFormat");
    _Static_assert(offsetof(WINDOWPLACEMENT, length) == 0, "WINDOWPLACEMENT.length");
    _Static_assert(offsetof(WINDOWPLACEMENT, flags) == 4, "WINDOWPLACEMENT.flags");
    _Static_assert(offsetof(WINDOWPLACEMENT, showCmd) == 8, "WINDOWPLACEMENT.showCmd");
    _Static_assert(offsetof(WINDOWPLACEMENT, ptMinPosition) == 12, "WINDOWPLACEMENT.ptMinPosition");
    _Static_assert(offsetof(WINDOWPLACEMENT, ptMaxPosition) == 20, "WINDOWPLACEMENT.ptMaxPosition");
    _Static_assert(offsetof(WINDOWPLACEMENT, rcNormalPosition) == 28, "WINDOWPLACEMENT.rcNormalPosition");
    _Static_assert(offsetof(NONCLIENTMETRICSW, cbSize) == 0, "NONCLIENTMETRICSW.cbSize");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iBorderWidth) == 4, "NONCLIENTMETRICSW.iBorderWidth");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iScrollWidth) == 8, "NONCLIENTMETRICSW.iScrollWidth");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iScrollHeight) == 12, "NONCLIENTMETRICSW.iScrollHeight");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iCaptionWidth) == 16, "NONCLIENTMETRICSW.iCaptionWidth");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iCaptionHeight) == 20, "NONCLIENTMETRICSW.iCaptionHeight");
    _Static_assert(offsetof(LOGFONTW, lfHeight) == 0, "LOGFONTW.lfHeight");
    _Static_assert(offsetof(LOGFONTW, lfWidth) == 4, "LOGFONTW.lfWidth");
    _Static_assert(offsetof(LOGFONTW, lfEscapement) == 8, "LOGFONTW.lfEscapement");
    _Static_assert(offsetof(LOGFONTW, lfOrientation) == 12, "LOGFONTW.lfOrientation");
    _Static_assert(offsetof(LOGFONTW, lfWeight) == 16, "LOGFONTW.lfWeight");
    _Static_assert(offsetof(LOGFONTW, lfItalic) == 20, "LOGFONTW.lfItalic");
    _Static_assert(offsetof(LOGFONTW, lfUnderline) == 21, "LOGFONTW.lfUnderline");
    _Static_assert(offsetof(LOGFONTW, lfStrikeOut) == 22, "LOGFONTW.lfStrikeOut");
    _Static_assert(offsetof(LOGFONTW, lfCharSet) == 23, "LOGFONTW.lfCharSet");
    _Static_assert(offsetof(LOGFONTW, lfOutPrecision) == 24, "LOGFONTW.lfOutPrecision");
    _Static_assert(offsetof(LOGFONTW, lfClipPrecision) == 25, "LOGFONTW.lfClipPrecision");
    _Static_assert(offsetof(LOGFONTW, lfQuality) == 26, "LOGFONTW.lfQuality");
    _Static_assert(offsetof(LOGFONTW, lfPitchAndFamily) == 27, "LOGFONTW.lfPitchAndFamily");
    _Static_assert(offsetof(LOGFONTW, lfFaceName) == 28, "LOGFONTW.lfFaceName");
    _Static_assert(offsetof(NONCLIENTMETRICSW, lfCaptionFont) == 24, "NONCLIENTMETRICSW.lfCaptionFont");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iSmCaptionWidth) == 116, "NONCLIENTMETRICSW.iSmCaptionWidth");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iSmCaptionHeight) == 120, "NONCLIENTMETRICSW.iSmCaptionHeight");
    _Static_assert(offsetof(NONCLIENTMETRICSW, lfSmCaptionFont) == 124, "NONCLIENTMETRICSW.lfSmCaptionFont");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iMenuWidth) == 216, "NONCLIENTMETRICSW.iMenuWidth");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iMenuHeight) == 220, "NONCLIENTMETRICSW.iMenuHeight");
    _Static_assert(offsetof(NONCLIENTMETRICSW, lfMenuFont) == 224, "NONCLIENTMETRICSW.lfMenuFont");
    _Static_assert(offsetof(NONCLIENTMETRICSW, lfStatusFont) == 316, "NONCLIENTMETRICSW.lfStatusFont");
    _Static_assert(offsetof(NONCLIENTMETRICSW, lfMessageFont) == 408, "NONCLIENTMETRICSW.lfMessageFont");
    _Static_assert(offsetof(NONCLIENTMETRICSW, iPaddedBorderWidth) == 500, "NONCLIENTMETRICSW.iPaddedBorderWidth");
    _Static_assert(offsetof(HIGHCONTRASTW, cbSize) == 0, "HIGHCONTRASTW.cbSize");
    _Static_assert(offsetof(HIGHCONTRASTW, dwFlags) == 4, "HIGHCONTRASTW.dwFlags");
    _Static_assert(offsetof(HIGHCONTRASTW, lpszDefaultScheme) == 8, "HIGHCONTRASTW.lpszDefaultScheme");
    _Static_assert(offsetof(OPENFILENAMEW, lStructSize) == 0, "OPENFILENAMEW.lStructSize");
    _Static_assert(offsetof(OPENFILENAMEW, hwndOwner) == 8, "OPENFILENAMEW.hwndOwner");
    _Static_assert(offsetof(OPENFILENAMEW, hInstance) == 16, "OPENFILENAMEW.hInstance");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrFilter) == 24, "OPENFILENAMEW.lpstrFilter");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrCustomFilter) == 32, "OPENFILENAMEW.lpstrCustomFilter");
    _Static_assert(offsetof(OPENFILENAMEW, nMaxCustFilter) == 40, "OPENFILENAMEW.nMaxCustFilter");
    _Static_assert(offsetof(OPENFILENAMEW, nFilterIndex) == 44, "OPENFILENAMEW.nFilterIndex");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrFile) == 48, "OPENFILENAMEW.lpstrFile");
    _Static_assert(offsetof(OPENFILENAMEW, nMaxFile) == 56, "OPENFILENAMEW.nMaxFile");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrFileTitle) == 64, "OPENFILENAMEW.lpstrFileTitle");
    _Static_assert(offsetof(OPENFILENAMEW, nMaxFileTitle) == 72, "OPENFILENAMEW.nMaxFileTitle");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrInitialDir) == 80, "OPENFILENAMEW.lpstrInitialDir");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrTitle) == 88, "OPENFILENAMEW.lpstrTitle");
    _Static_assert(offsetof(OPENFILENAMEW, Flags) == 96, "OPENFILENAMEW.Flags");
    _Static_assert(offsetof(OPENFILENAMEW, nFileOffset) == 100, "OPENFILENAMEW.nFileOffset");
    _Static_assert(offsetof(OPENFILENAMEW, nFileExtension) == 102, "OPENFILENAMEW.nFileExtension");
    _Static_assert(offsetof(OPENFILENAMEW, lpstrDefExt) == 104, "OPENFILENAMEW.lpstrDefExt");
    _Static_assert(offsetof(OPENFILENAMEW, lCustData) == 112, "OPENFILENAMEW.lCustData");
    _Static_assert(offsetof(OPENFILENAMEW, lpfnHook) == 120, "OPENFILENAMEW.lpfnHook");
    _Static_assert(offsetof(OPENFILENAMEW, lpTemplateName) == 128, "OPENFILENAMEW.lpTemplateName");
    _Static_assert(offsetof(OPENFILENAMEW, pvReserved) == 136, "OPENFILENAMEW.pvReserved");
    _Static_assert(offsetof(OPENFILENAMEW, dwReserved) == 144, "OPENFILENAMEW.dwReserved");
    _Static_assert(offsetof(OPENFILENAMEW, FlagsEx) == 148, "OPENFILENAMEW.FlagsEx");
    _Static_assert(offsetof(WIN32_FIND_DATAW, dwFileAttributes) == 0, "WIN32_FIND_DATAW.dwFileAttributes");
    _Static_assert(offsetof(FILETIME, dwLowDateTime) == 0, "FILETIME.dwLowDateTime");
    _Static_assert(offsetof(FILETIME, dwHighDateTime) == 4, "FILETIME.dwHighDateTime");
    _Static_assert(offsetof(WIN32_FIND_DATAW, ftCreationTime) == 4, "WIN32_FIND_DATAW.ftCreationTime");
    _Static_assert(offsetof(WIN32_FIND_DATAW, ftLastAccessTime) == 12, "WIN32_FIND_DATAW.ftLastAccessTime");
    _Static_assert(offsetof(WIN32_FIND_DATAW, ftLastWriteTime) == 20, "WIN32_FIND_DATAW.ftLastWriteTime");
    _Static_assert(offsetof(WIN32_FIND_DATAW, nFileSizeHigh) == 28, "WIN32_FIND_DATAW.nFileSizeHigh");
    _Static_assert(offsetof(WIN32_FIND_DATAW, nFileSizeLow) == 32, "WIN32_FIND_DATAW.nFileSizeLow");
    _Static_assert(offsetof(WIN32_FIND_DATAW, dwReserved0) == 36, "WIN32_FIND_DATAW.dwReserved0");
    _Static_assert(offsetof(WIN32_FIND_DATAW, dwReserved1) == 40, "WIN32_FIND_DATAW.dwReserved1");
    _Static_assert(offsetof(WIN32_FIND_DATAW, cFileName) == 44, "WIN32_FIND_DATAW.cFileName");
    _Static_assert(offsetof(WIN32_FIND_DATAW, cAlternateFileName) == 564, "WIN32_FIND_DATAW.cAlternateFileName");
    _Static_assert(offsetof(COMPOSITIONFORM, dwStyle) == 0, "COMPOSITIONFORM.dwStyle");
    _Static_assert(offsetof(COMPOSITIONFORM, ptCurrentPos) == 4, "COMPOSITIONFORM.ptCurrentPos");
    _Static_assert(offsetof(COMPOSITIONFORM, rcArea) == 12, "COMPOSITIONFORM.rcArea");
    _Static_assert(offsetof(CANDIDATEFORM, dwIndex) == 0, "CANDIDATEFORM.dwIndex");
    _Static_assert(offsetof(CANDIDATEFORM, dwStyle) == 4, "CANDIDATEFORM.dwStyle");
    _Static_assert(offsetof(CANDIDATEFORM, ptCurrentPos) == 8, "CANDIDATEFORM.ptCurrentPos");
    _Static_assert(offsetof(CANDIDATEFORM, rcArea) == 16, "CANDIDATEFORM.rcArea");
    _Static_assert(offsetof(NOTIFYICONDATAW, cbSize) == 0, "NOTIFYICONDATAW.cbSize");
    _Static_assert(offsetof(NOTIFYICONDATAW, hWnd) == 8, "NOTIFYICONDATAW.hWnd");
    _Static_assert(offsetof(NOTIFYICONDATAW, uID) == 16, "NOTIFYICONDATAW.uID");
    _Static_assert(offsetof(NOTIFYICONDATAW, uFlags) == 20, "NOTIFYICONDATAW.uFlags");
    _Static_assert(offsetof(NOTIFYICONDATAW, uCallbackMessage) == 24, "NOTIFYICONDATAW.uCallbackMessage");
    _Static_assert(offsetof(NOTIFYICONDATAW, hIcon) == 32, "NOTIFYICONDATAW.hIcon");
    _Static_assert(offsetof(NOTIFYICONDATAW, szTip) == 40, "NOTIFYICONDATAW.szTip");
    _Static_assert(offsetof(NOTIFYICONDATAW, dwState) == 296, "NOTIFYICONDATAW.dwState");
    _Static_assert(offsetof(NOTIFYICONDATAW, dwStateMask) == 300, "NOTIFYICONDATAW.dwStateMask");
    _Static_assert(offsetof(NOTIFYICONDATAW, szInfo) == 304, "NOTIFYICONDATAW.szInfo");
    _Static_assert(offsetof(NOTIFYICONDATAW, szInfoTitle) == 820, "NOTIFYICONDATAW.szInfoTitle");
    _Static_assert(offsetof(NOTIFYICONDATAW, dwInfoFlags) == 948, "NOTIFYICONDATAW.dwInfoFlags");
    _Static_assert(offsetof(GUID, Data1) == 0, "GUID.Data1");
    _Static_assert(offsetof(GUID, Data2) == 4, "GUID.Data2");
    _Static_assert(offsetof(GUID, Data3) == 6, "GUID.Data3");
    _Static_assert(offsetof(GUID, Data4) == 8, "GUID.Data4");
    _Static_assert(offsetof(NOTIFYICONDATAW, guidItem) == 952, "NOTIFYICONDATAW.guidItem");
    _Static_assert(offsetof(NOTIFYICONDATAW, hBalloonIcon) == 968, "NOTIFYICONDATAW.hBalloonIcon");
    _Static_assert(offsetof(FORMATETC, cfFormat) == 0, "FORMATETC.cfFormat");
    _Static_assert(offsetof(FORMATETC, ptd) == 8, "FORMATETC.ptd");
    _Static_assert(offsetof(FORMATETC, dwAspect) == 16, "FORMATETC.dwAspect");
    _Static_assert(offsetof(FORMATETC, lindex) == 20, "FORMATETC.lindex");
    _Static_assert(offsetof(FORMATETC, tymed) == 24, "FORMATETC.tymed");
    _Static_assert(offsetof(STGMEDIUM, tymed) == 0, "STGMEDIUM.tymed");
    _Static_assert(offsetof(STGMEDIUM, pUnkForRelease) == 16, "STGMEDIUM.pUnkForRelease");
    _Static_assert(offsetof(SAFEARRAY, cDims) == 0, "SAFEARRAY.cDims");
    _Static_assert(offsetof(SAFEARRAY, fFeatures) == 2, "SAFEARRAY.fFeatures");
    _Static_assert(offsetof(SAFEARRAY, cbElements) == 4, "SAFEARRAY.cbElements");
    _Static_assert(offsetof(SAFEARRAY, cLocks) == 8, "SAFEARRAY.cLocks");
    _Static_assert(offsetof(SAFEARRAY, pvData) == 16, "SAFEARRAY.pvData");
    _Static_assert(offsetof(SAFEARRAYBOUND, cElements) == 0, "SAFEARRAYBOUND.cElements");
    _Static_assert(offsetof(SAFEARRAYBOUND, lLbound) == 4, "SAFEARRAYBOUND.lLbound");
    _Static_assert(offsetof(SAFEARRAY, rgsabound) == 24, "SAFEARRAY.rgsabound");
    _Static_assert(offsetof(COMDLG_FILTERSPEC, pszName) == 0, "COMDLG_FILTERSPEC.pszName");
    _Static_assert(offsetof(COMDLG_FILTERSPEC, pszSpec) == 8, "COMDLG_FILTERSPEC.pszSpec");
    _Static_assert(offsetof(DISPPARAMS, rgvarg) == 0, "DISPPARAMS.rgvarg");
    _Static_assert(offsetof(DISPPARAMS, rgdispidNamedArgs) == 8, "DISPPARAMS.rgdispidNamedArgs");
    _Static_assert(offsetof(DISPPARAMS, cArgs) == 16, "DISPPARAMS.cArgs");
    _Static_assert(offsetof(DISPPARAMS, cNamedArgs) == 20, "DISPPARAMS.cNamedArgs");
    _Static_assert(offsetof(EXCEPINFO, wCode) == 0, "EXCEPINFO.wCode");
    _Static_assert(offsetof(EXCEPINFO, wReserved) == 2, "EXCEPINFO.wReserved");
    _Static_assert(offsetof(EXCEPINFO, bstrSource) == 8, "EXCEPINFO.bstrSource");
    _Static_assert(offsetof(EXCEPINFO, bstrDescription) == 16, "EXCEPINFO.bstrDescription");
    _Static_assert(offsetof(EXCEPINFO, bstrHelpFile) == 24, "EXCEPINFO.bstrHelpFile");
    _Static_assert(offsetof(EXCEPINFO, dwHelpContext) == 32, "EXCEPINFO.dwHelpContext");
    _Static_assert(offsetof(EXCEPINFO, pvReserved) == 40, "EXCEPINFO.pvReserved");
    _Static_assert(offsetof(EXCEPINFO, pfnDeferredFillIn) == 48, "EXCEPINFO.pfnDeferredFillIn");
    _Static_assert(offsetof(EXCEPINFO, scode) == 56, "EXCEPINFO.scode");
    _Static_assert(offsetof(INPUT, type) == 0, "INPUT.type");
    _Static_assert(offsetof(MARGINS, cxLeftWidth) == 0, "MARGINS.cxLeftWidth");
    _Static_assert(offsetof(MARGINS, cxRightWidth) == 4, "MARGINS.cxRightWidth");
    _Static_assert(offsetof(MARGINS, cyTopHeight) == 8, "MARGINS.cyTopHeight");
    _Static_assert(offsetof(MARGINS, cyBottomHeight) == 12, "MARGINS.cyBottomHeight");
    _Static_assert(offsetof(MONITORINFO, cbSize) == 0, "MONITORINFO.cbSize");
    _Static_assert(offsetof(MONITORINFO, rcMonitor) == 4, "MONITORINFO.rcMonitor");
    _Static_assert(offsetof(MONITORINFO, rcWork) == 20, "MONITORINFO.rcWork");
    _Static_assert(offsetof(MONITORINFO, dwFlags) == 36, "MONITORINFO.dwFlags");
    _Static_assert(offsetof(IUnknownVtbl, QueryInterface) == 0, "IUnknownVtbl.QueryInterface");
    _Static_assert(offsetof(IUnknownVtbl, AddRef) == 8, "IUnknownVtbl.AddRef");
    _Static_assert(offsetof(IUnknownVtbl, Release) == 16, "IUnknownVtbl.Release");
    _Static_assert(offsetof(IUnknown, lpVtbl) == 0, "IUnknown.lpVtbl");
    _Static_assert(offsetof(IDropTargetVtbl, QueryInterface) == 0, "IDropTargetVtbl.QueryInterface");
    _Static_assert(offsetof(IDropTargetVtbl, AddRef) == 8, "IDropTargetVtbl.AddRef");
    _Static_assert(offsetof(IDropTargetVtbl, Release) == 16, "IDropTargetVtbl.Release");
    _Static_assert(offsetof(IDropTargetVtbl, DragEnter) == 24, "IDropTargetVtbl.DragEnter");
    _Static_assert(offsetof(IDropTargetVtbl, DragOver) == 32, "IDropTargetVtbl.DragOver");
    _Static_assert(offsetof(IDropTargetVtbl, DragLeave) == 40, "IDropTargetVtbl.DragLeave");
    _Static_assert(offsetof(IDropTargetVtbl, Drop) == 48, "IDropTargetVtbl.Drop");
    _Static_assert(offsetof(IDropTarget, lpVtbl) == 0, "IDropTarget.lpVtbl");
    _Static_assert(offsetof(IDataObjectVtbl, QueryInterface) == 0, "IDataObjectVtbl.QueryInterface");
    _Static_assert(offsetof(IDataObjectVtbl, AddRef) == 8, "IDataObjectVtbl.AddRef");
    _Static_assert(offsetof(IDataObjectVtbl, Release) == 16, "IDataObjectVtbl.Release");
    _Static_assert(offsetof(IDataObjectVtbl, GetData) == 24, "IDataObjectVtbl.GetData");
    _Static_assert(offsetof(IDataObjectVtbl, GetDataHere) == 32, "IDataObjectVtbl.GetDataHere");
    _Static_assert(offsetof(IDataObjectVtbl, QueryGetData) == 40, "IDataObjectVtbl.QueryGetData");
    _Static_assert(offsetof(IDataObjectVtbl, GetCanonicalFormatEtc) == 48, "IDataObjectVtbl.GetCanonicalFormatEtc");
    _Static_assert(offsetof(IDataObjectVtbl, SetData) == 56, "IDataObjectVtbl.SetData");
    _Static_assert(offsetof(IDataObjectVtbl, EnumFormatEtc) == 64, "IDataObjectVtbl.EnumFormatEtc");
    _Static_assert(offsetof(IDataObjectVtbl, DAdvise) == 72, "IDataObjectVtbl.DAdvise");
    _Static_assert(offsetof(IDataObjectVtbl, DUnadvise) == 80, "IDataObjectVtbl.DUnadvise");
    _Static_assert(offsetof(IDataObjectVtbl, EnumDAdvise) == 88, "IDataObjectVtbl.EnumDAdvise");
    _Static_assert(offsetof(IDataObject, lpVtbl) == 0, "IDataObject.lpVtbl");
    _Static_assert(offsetof(IDropSourceVtbl, QueryInterface) == 0, "IDropSourceVtbl.QueryInterface");
    _Static_assert(offsetof(IDropSourceVtbl, AddRef) == 8, "IDropSourceVtbl.AddRef");
    _Static_assert(offsetof(IDropSourceVtbl, Release) == 16, "IDropSourceVtbl.Release");
    _Static_assert(offsetof(IDropSourceVtbl, QueryContinueDrag) == 24, "IDropSourceVtbl.QueryContinueDrag");
    _Static_assert(offsetof(IDropSourceVtbl, GiveFeedback) == 32, "IDropSourceVtbl.GiveFeedback");
    _Static_assert(offsetof(IDropSource, lpVtbl) == 0, "IDropSource.lpVtbl");
    _Static_assert(offsetof(IFileOpenDialogVtbl, QueryInterface) == 0, "IFileOpenDialogVtbl.QueryInterface");
    _Static_assert(offsetof(IFileOpenDialogVtbl, AddRef) == 8, "IFileOpenDialogVtbl.AddRef");
    _Static_assert(offsetof(IFileOpenDialogVtbl, Release) == 16, "IFileOpenDialogVtbl.Release");
    _Static_assert(offsetof(IFileOpenDialogVtbl, Show) == 24, "IFileOpenDialogVtbl.Show");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetFileTypes) == 32, "IFileOpenDialogVtbl.SetFileTypes");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetFileTypeIndex) == 40, "IFileOpenDialogVtbl.SetFileTypeIndex");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetFileTypeIndex) == 48, "IFileOpenDialogVtbl.GetFileTypeIndex");
    _Static_assert(offsetof(IFileOpenDialogVtbl, Advise) == 56, "IFileOpenDialogVtbl.Advise");
    _Static_assert(offsetof(IFileOpenDialogVtbl, Unadvise) == 64, "IFileOpenDialogVtbl.Unadvise");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetOptions) == 72, "IFileOpenDialogVtbl.SetOptions");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetOptions) == 80, "IFileOpenDialogVtbl.GetOptions");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetDefaultFolder) == 88, "IFileOpenDialogVtbl.SetDefaultFolder");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetFolder) == 96, "IFileOpenDialogVtbl.SetFolder");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetFolder) == 104, "IFileOpenDialogVtbl.GetFolder");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetCurrentSelection) == 112, "IFileOpenDialogVtbl.GetCurrentSelection");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetFileName) == 120, "IFileOpenDialogVtbl.SetFileName");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetFileName) == 128, "IFileOpenDialogVtbl.GetFileName");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetTitle) == 136, "IFileOpenDialogVtbl.SetTitle");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetOkButtonLabel) == 144, "IFileOpenDialogVtbl.SetOkButtonLabel");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetFileNameLabel) == 152, "IFileOpenDialogVtbl.SetFileNameLabel");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetResult) == 160, "IFileOpenDialogVtbl.GetResult");
    _Static_assert(offsetof(IFileOpenDialogVtbl, AddPlace) == 168, "IFileOpenDialogVtbl.AddPlace");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetDefaultExtension) == 176, "IFileOpenDialogVtbl.SetDefaultExtension");
    _Static_assert(offsetof(IFileOpenDialogVtbl, Close) == 184, "IFileOpenDialogVtbl.Close");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetClientGuid) == 192, "IFileOpenDialogVtbl.SetClientGuid");
    _Static_assert(offsetof(IFileOpenDialogVtbl, ClearClientData) == 200, "IFileOpenDialogVtbl.ClearClientData");
    _Static_assert(offsetof(IFileOpenDialogVtbl, SetFilter) == 208, "IFileOpenDialogVtbl.SetFilter");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetResults) == 216, "IFileOpenDialogVtbl.GetResults");
    _Static_assert(offsetof(IFileOpenDialogVtbl, GetSelectedItems) == 224, "IFileOpenDialogVtbl.GetSelectedItems");
    _Static_assert(offsetof(IFileOpenDialog, lpVtbl) == 0, "IFileOpenDialog.lpVtbl");
    _Static_assert(offsetof(IFileSaveDialogVtbl, QueryInterface) == 0, "IFileSaveDialogVtbl.QueryInterface");
    _Static_assert(offsetof(IFileSaveDialogVtbl, AddRef) == 8, "IFileSaveDialogVtbl.AddRef");
    _Static_assert(offsetof(IFileSaveDialogVtbl, Release) == 16, "IFileSaveDialogVtbl.Release");
    _Static_assert(offsetof(IFileSaveDialogVtbl, Show) == 24, "IFileSaveDialogVtbl.Show");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetFileTypes) == 32, "IFileSaveDialogVtbl.SetFileTypes");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetFileTypeIndex) == 40, "IFileSaveDialogVtbl.SetFileTypeIndex");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetFileTypeIndex) == 48, "IFileSaveDialogVtbl.GetFileTypeIndex");
    _Static_assert(offsetof(IFileSaveDialogVtbl, Advise) == 56, "IFileSaveDialogVtbl.Advise");
    _Static_assert(offsetof(IFileSaveDialogVtbl, Unadvise) == 64, "IFileSaveDialogVtbl.Unadvise");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetOptions) == 72, "IFileSaveDialogVtbl.SetOptions");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetOptions) == 80, "IFileSaveDialogVtbl.GetOptions");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetDefaultFolder) == 88, "IFileSaveDialogVtbl.SetDefaultFolder");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetFolder) == 96, "IFileSaveDialogVtbl.SetFolder");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetFolder) == 104, "IFileSaveDialogVtbl.GetFolder");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetCurrentSelection) == 112, "IFileSaveDialogVtbl.GetCurrentSelection");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetFileName) == 120, "IFileSaveDialogVtbl.SetFileName");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetFileName) == 128, "IFileSaveDialogVtbl.GetFileName");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetTitle) == 136, "IFileSaveDialogVtbl.SetTitle");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetOkButtonLabel) == 144, "IFileSaveDialogVtbl.SetOkButtonLabel");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetFileNameLabel) == 152, "IFileSaveDialogVtbl.SetFileNameLabel");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetResult) == 160, "IFileSaveDialogVtbl.GetResult");
    _Static_assert(offsetof(IFileSaveDialogVtbl, AddPlace) == 168, "IFileSaveDialogVtbl.AddPlace");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetDefaultExtension) == 176, "IFileSaveDialogVtbl.SetDefaultExtension");
    _Static_assert(offsetof(IFileSaveDialogVtbl, Close) == 184, "IFileSaveDialogVtbl.Close");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetClientGuid) == 192, "IFileSaveDialogVtbl.SetClientGuid");
    _Static_assert(offsetof(IFileSaveDialogVtbl, ClearClientData) == 200, "IFileSaveDialogVtbl.ClearClientData");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetFilter) == 208, "IFileSaveDialogVtbl.SetFilter");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetSaveAsItem) == 216, "IFileSaveDialogVtbl.SetSaveAsItem");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetProperties) == 224, "IFileSaveDialogVtbl.SetProperties");
    _Static_assert(offsetof(IFileSaveDialogVtbl, SetCollectedProperties) == 232, "IFileSaveDialogVtbl.SetCollectedProperties");
    _Static_assert(offsetof(IFileSaveDialogVtbl, GetProperties) == 240, "IFileSaveDialogVtbl.GetProperties");
    _Static_assert(offsetof(IFileSaveDialogVtbl, ApplyProperties) == 248, "IFileSaveDialogVtbl.ApplyProperties");
    _Static_assert(offsetof(IFileSaveDialog, lpVtbl) == 0, "IFileSaveDialog.lpVtbl");
    _Static_assert(offsetof(IShellItemVtbl, QueryInterface) == 0, "IShellItemVtbl.QueryInterface");
    _Static_assert(offsetof(IShellItemVtbl, AddRef) == 8, "IShellItemVtbl.AddRef");
    _Static_assert(offsetof(IShellItemVtbl, Release) == 16, "IShellItemVtbl.Release");
    _Static_assert(offsetof(IShellItemVtbl, BindToHandler) == 24, "IShellItemVtbl.BindToHandler");
    _Static_assert(offsetof(IShellItemVtbl, GetParent) == 32, "IShellItemVtbl.GetParent");
    _Static_assert(offsetof(IShellItemVtbl, GetDisplayName) == 40, "IShellItemVtbl.GetDisplayName");
    _Static_assert(offsetof(IShellItemVtbl, GetAttributes) == 48, "IShellItemVtbl.GetAttributes");
    _Static_assert(offsetof(IShellItemVtbl, Compare) == 56, "IShellItemVtbl.Compare");
    _Static_assert(offsetof(IShellItem, lpVtbl) == 0, "IShellItem.lpVtbl");
    _Static_assert(offsetof(IShellItemArrayVtbl, QueryInterface) == 0, "IShellItemArrayVtbl.QueryInterface");
    _Static_assert(offsetof(IShellItemArrayVtbl, AddRef) == 8, "IShellItemArrayVtbl.AddRef");
    _Static_assert(offsetof(IShellItemArrayVtbl, Release) == 16, "IShellItemArrayVtbl.Release");
    _Static_assert(offsetof(IShellItemArrayVtbl, BindToHandler) == 24, "IShellItemArrayVtbl.BindToHandler");
    _Static_assert(offsetof(IShellItemArrayVtbl, GetPropertyStore) == 32, "IShellItemArrayVtbl.GetPropertyStore");
    _Static_assert(offsetof(IShellItemArrayVtbl, GetPropertyDescriptionList) == 40, "IShellItemArrayVtbl.GetPropertyDescriptionList");
    _Static_assert(offsetof(IShellItemArrayVtbl, GetAttributes) == 48, "IShellItemArrayVtbl.GetAttributes");
    _Static_assert(offsetof(IShellItemArrayVtbl, GetCount) == 56, "IShellItemArrayVtbl.GetCount");
    _Static_assert(offsetof(IShellItemArrayVtbl, GetItemAt) == 64, "IShellItemArrayVtbl.GetItemAt");
    _Static_assert(offsetof(IShellItemArrayVtbl, EnumItems) == 72, "IShellItemArrayVtbl.EnumItems");
    _Static_assert(offsetof(IShellItemArray, lpVtbl) == 0, "IShellItemArray.lpVtbl");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, QueryInterface) == 0, "IRawElementProviderSimpleVtbl.QueryInterface");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, AddRef) == 8, "IRawElementProviderSimpleVtbl.AddRef");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, Release) == 16, "IRawElementProviderSimpleVtbl.Release");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, get_ProviderOptions) == 24, "IRawElementProviderSimpleVtbl.get_ProviderOptions");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, GetPatternProvider) == 32, "IRawElementProviderSimpleVtbl.GetPatternProvider");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, GetPropertyValue) == 40, "IRawElementProviderSimpleVtbl.GetPropertyValue");
    _Static_assert(offsetof(IRawElementProviderSimpleVtbl, get_HostRawElementProvider) == 48, "IRawElementProviderSimpleVtbl.get_HostRawElementProvider");
    _Static_assert(offsetof(IRawElementProviderSimple, lpVtbl) == 0, "IRawElementProviderSimple.lpVtbl");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, QueryInterface) == 0, "IRawElementProviderFragmentVtbl.QueryInterface");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, AddRef) == 8, "IRawElementProviderFragmentVtbl.AddRef");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, Release) == 16, "IRawElementProviderFragmentVtbl.Release");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, Navigate) == 24, "IRawElementProviderFragmentVtbl.Navigate");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, GetRuntimeId) == 32, "IRawElementProviderFragmentVtbl.GetRuntimeId");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, get_BoundingRectangle) == 40, "IRawElementProviderFragmentVtbl.get_BoundingRectangle");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, GetEmbeddedFragmentRoots) == 48, "IRawElementProviderFragmentVtbl.GetEmbeddedFragmentRoots");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, SetFocus) == 56, "IRawElementProviderFragmentVtbl.SetFocus");
    _Static_assert(offsetof(IRawElementProviderFragmentVtbl, get_FragmentRoot) == 64, "IRawElementProviderFragmentVtbl.get_FragmentRoot");
    _Static_assert(offsetof(IRawElementProviderFragment, lpVtbl) == 0, "IRawElementProviderFragment.lpVtbl");
    _Static_assert(offsetof(IRawElementProviderFragmentRootVtbl, QueryInterface) == 0, "IRawElementProviderFragmentRootVtbl.QueryInterface");
    _Static_assert(offsetof(IRawElementProviderFragmentRootVtbl, AddRef) == 8, "IRawElementProviderFragmentRootVtbl.AddRef");
    _Static_assert(offsetof(IRawElementProviderFragmentRootVtbl, Release) == 16, "IRawElementProviderFragmentRootVtbl.Release");
    _Static_assert(offsetof(IRawElementProviderFragmentRootVtbl, ElementProviderFromPoint) == 24, "IRawElementProviderFragmentRootVtbl.ElementProviderFromPoint");
    _Static_assert(offsetof(IRawElementProviderFragmentRootVtbl, GetFocus) == 32, "IRawElementProviderFragmentRootVtbl.GetFocus");
    _Static_assert(offsetof(IRawElementProviderFragmentRoot, lpVtbl) == 0, "IRawElementProviderFragmentRoot.lpVtbl");
    _Static_assert(offsetof(IInvokeProviderVtbl, QueryInterface) == 0, "IInvokeProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IInvokeProviderVtbl, AddRef) == 8, "IInvokeProviderVtbl.AddRef");
    _Static_assert(offsetof(IInvokeProviderVtbl, Release) == 16, "IInvokeProviderVtbl.Release");
    _Static_assert(offsetof(IInvokeProviderVtbl, Invoke) == 24, "IInvokeProviderVtbl.Invoke");
    _Static_assert(offsetof(IInvokeProvider, lpVtbl) == 0, "IInvokeProvider.lpVtbl");
    _Static_assert(offsetof(IToggleProviderVtbl, QueryInterface) == 0, "IToggleProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IToggleProviderVtbl, AddRef) == 8, "IToggleProviderVtbl.AddRef");
    _Static_assert(offsetof(IToggleProviderVtbl, Release) == 16, "IToggleProviderVtbl.Release");
    _Static_assert(offsetof(IToggleProviderVtbl, Toggle) == 24, "IToggleProviderVtbl.Toggle");
    _Static_assert(offsetof(IToggleProviderVtbl, get_ToggleState) == 32, "IToggleProviderVtbl.get_ToggleState");
    _Static_assert(offsetof(IToggleProvider, lpVtbl) == 0, "IToggleProvider.lpVtbl");
    _Static_assert(offsetof(IValueProviderVtbl, QueryInterface) == 0, "IValueProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IValueProviderVtbl, AddRef) == 8, "IValueProviderVtbl.AddRef");
    _Static_assert(offsetof(IValueProviderVtbl, Release) == 16, "IValueProviderVtbl.Release");
    _Static_assert(offsetof(IValueProviderVtbl, SetValue) == 24, "IValueProviderVtbl.SetValue");
    _Static_assert(offsetof(IValueProviderVtbl, get_Value) == 32, "IValueProviderVtbl.get_Value");
    _Static_assert(offsetof(IValueProviderVtbl, get_IsReadOnly) == 40, "IValueProviderVtbl.get_IsReadOnly");
    _Static_assert(offsetof(IValueProvider, lpVtbl) == 0, "IValueProvider.lpVtbl");
    _Static_assert(offsetof(IRangeValueProviderVtbl, QueryInterface) == 0, "IRangeValueProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IRangeValueProviderVtbl, AddRef) == 8, "IRangeValueProviderVtbl.AddRef");
    _Static_assert(offsetof(IRangeValueProviderVtbl, Release) == 16, "IRangeValueProviderVtbl.Release");
    _Static_assert(offsetof(IRangeValueProviderVtbl, SetValue) == 24, "IRangeValueProviderVtbl.SetValue");
    _Static_assert(offsetof(IRangeValueProviderVtbl, get_Value) == 32, "IRangeValueProviderVtbl.get_Value");
    _Static_assert(offsetof(IRangeValueProviderVtbl, get_IsReadOnly) == 40, "IRangeValueProviderVtbl.get_IsReadOnly");
    _Static_assert(offsetof(IRangeValueProviderVtbl, get_Maximum) == 48, "IRangeValueProviderVtbl.get_Maximum");
    _Static_assert(offsetof(IRangeValueProviderVtbl, get_Minimum) == 56, "IRangeValueProviderVtbl.get_Minimum");
    _Static_assert(offsetof(IRangeValueProviderVtbl, get_LargeChange) == 64, "IRangeValueProviderVtbl.get_LargeChange");
    _Static_assert(offsetof(IRangeValueProviderVtbl, get_SmallChange) == 72, "IRangeValueProviderVtbl.get_SmallChange");
    _Static_assert(offsetof(IRangeValueProvider, lpVtbl) == 0, "IRangeValueProvider.lpVtbl");
    _Static_assert(offsetof(ITextProviderVtbl, QueryInterface) == 0, "ITextProviderVtbl.QueryInterface");
    _Static_assert(offsetof(ITextProviderVtbl, AddRef) == 8, "ITextProviderVtbl.AddRef");
    _Static_assert(offsetof(ITextProviderVtbl, Release) == 16, "ITextProviderVtbl.Release");
    _Static_assert(offsetof(ITextProviderVtbl, GetSelection) == 24, "ITextProviderVtbl.GetSelection");
    _Static_assert(offsetof(ITextProviderVtbl, GetVisibleRanges) == 32, "ITextProviderVtbl.GetVisibleRanges");
    _Static_assert(offsetof(ITextProviderVtbl, RangeFromChild) == 40, "ITextProviderVtbl.RangeFromChild");
    _Static_assert(offsetof(ITextProviderVtbl, RangeFromPoint) == 48, "ITextProviderVtbl.RangeFromPoint");
    _Static_assert(offsetof(ITextProviderVtbl, get_DocumentRange) == 56, "ITextProviderVtbl.get_DocumentRange");
    _Static_assert(offsetof(ITextProviderVtbl, get_SupportedTextSelection) == 64, "ITextProviderVtbl.get_SupportedTextSelection");
    _Static_assert(offsetof(ITextProvider, lpVtbl) == 0, "ITextProvider.lpVtbl");
    _Static_assert(offsetof(ITextRangeProviderVtbl, QueryInterface) == 0, "ITextRangeProviderVtbl.QueryInterface");
    _Static_assert(offsetof(ITextRangeProviderVtbl, AddRef) == 8, "ITextRangeProviderVtbl.AddRef");
    _Static_assert(offsetof(ITextRangeProviderVtbl, Release) == 16, "ITextRangeProviderVtbl.Release");
    _Static_assert(offsetof(ITextRangeProviderVtbl, Clone) == 24, "ITextRangeProviderVtbl.Clone");
    _Static_assert(offsetof(ITextRangeProviderVtbl, Compare) == 32, "ITextRangeProviderVtbl.Compare");
    _Static_assert(offsetof(ITextRangeProviderVtbl, CompareEndpoints) == 40, "ITextRangeProviderVtbl.CompareEndpoints");
    _Static_assert(offsetof(ITextRangeProviderVtbl, ExpandToEnclosingUnit) == 48, "ITextRangeProviderVtbl.ExpandToEnclosingUnit");
    _Static_assert(offsetof(ITextRangeProviderVtbl, FindAttribute) == 56, "ITextRangeProviderVtbl.FindAttribute");
    _Static_assert(offsetof(ITextRangeProviderVtbl, FindTextW) == 64, "ITextRangeProviderVtbl.FindTextW");
    _Static_assert(offsetof(ITextRangeProviderVtbl, GetAttributeValue) == 72, "ITextRangeProviderVtbl.GetAttributeValue");
    _Static_assert(offsetof(ITextRangeProviderVtbl, GetBoundingRectangles) == 80, "ITextRangeProviderVtbl.GetBoundingRectangles");
    _Static_assert(offsetof(ITextRangeProviderVtbl, GetEnclosingElement) == 88, "ITextRangeProviderVtbl.GetEnclosingElement");
    _Static_assert(offsetof(ITextRangeProviderVtbl, GetText) == 96, "ITextRangeProviderVtbl.GetText");
    _Static_assert(offsetof(ITextRangeProviderVtbl, Move) == 104, "ITextRangeProviderVtbl.Move");
    _Static_assert(offsetof(ITextRangeProviderVtbl, MoveEndpointByUnit) == 112, "ITextRangeProviderVtbl.MoveEndpointByUnit");
    _Static_assert(offsetof(ITextRangeProviderVtbl, MoveEndpointByRange) == 120, "ITextRangeProviderVtbl.MoveEndpointByRange");
    _Static_assert(offsetof(ITextRangeProviderVtbl, Select) == 128, "ITextRangeProviderVtbl.Select");
    _Static_assert(offsetof(ITextRangeProviderVtbl, AddToSelection) == 136, "ITextRangeProviderVtbl.AddToSelection");
    _Static_assert(offsetof(ITextRangeProviderVtbl, RemoveFromSelection) == 144, "ITextRangeProviderVtbl.RemoveFromSelection");
    _Static_assert(offsetof(ITextRangeProviderVtbl, ScrollIntoView) == 152, "ITextRangeProviderVtbl.ScrollIntoView");
    _Static_assert(offsetof(ITextRangeProviderVtbl, GetChildren) == 160, "ITextRangeProviderVtbl.GetChildren");
    _Static_assert(offsetof(ITextRangeProvider, lpVtbl) == 0, "ITextRangeProvider.lpVtbl");
    _Static_assert(offsetof(ISelectionProviderVtbl, QueryInterface) == 0, "ISelectionProviderVtbl.QueryInterface");
    _Static_assert(offsetof(ISelectionProviderVtbl, AddRef) == 8, "ISelectionProviderVtbl.AddRef");
    _Static_assert(offsetof(ISelectionProviderVtbl, Release) == 16, "ISelectionProviderVtbl.Release");
    _Static_assert(offsetof(ISelectionProviderVtbl, GetSelection) == 24, "ISelectionProviderVtbl.GetSelection");
    _Static_assert(offsetof(ISelectionProviderVtbl, get_CanSelectMultiple) == 32, "ISelectionProviderVtbl.get_CanSelectMultiple");
    _Static_assert(offsetof(ISelectionProviderVtbl, get_IsSelectionRequired) == 40, "ISelectionProviderVtbl.get_IsSelectionRequired");
    _Static_assert(offsetof(ISelectionProvider, lpVtbl) == 0, "ISelectionProvider.lpVtbl");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, QueryInterface) == 0, "ISelectionItemProviderVtbl.QueryInterface");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, AddRef) == 8, "ISelectionItemProviderVtbl.AddRef");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, Release) == 16, "ISelectionItemProviderVtbl.Release");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, Select) == 24, "ISelectionItemProviderVtbl.Select");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, AddToSelection) == 32, "ISelectionItemProviderVtbl.AddToSelection");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, RemoveFromSelection) == 40, "ISelectionItemProviderVtbl.RemoveFromSelection");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, get_IsSelected) == 48, "ISelectionItemProviderVtbl.get_IsSelected");
    _Static_assert(offsetof(ISelectionItemProviderVtbl, get_SelectionContainer) == 56, "ISelectionItemProviderVtbl.get_SelectionContainer");
    _Static_assert(offsetof(ISelectionItemProvider, lpVtbl) == 0, "ISelectionItemProvider.lpVtbl");
    _Static_assert(offsetof(IExpandCollapseProviderVtbl, QueryInterface) == 0, "IExpandCollapseProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IExpandCollapseProviderVtbl, AddRef) == 8, "IExpandCollapseProviderVtbl.AddRef");
    _Static_assert(offsetof(IExpandCollapseProviderVtbl, Release) == 16, "IExpandCollapseProviderVtbl.Release");
    _Static_assert(offsetof(IExpandCollapseProviderVtbl, Expand) == 24, "IExpandCollapseProviderVtbl.Expand");
    _Static_assert(offsetof(IExpandCollapseProviderVtbl, Collapse) == 32, "IExpandCollapseProviderVtbl.Collapse");
    _Static_assert(offsetof(IExpandCollapseProviderVtbl, get_ExpandCollapseState) == 40, "IExpandCollapseProviderVtbl.get_ExpandCollapseState");
    _Static_assert(offsetof(IExpandCollapseProvider, lpVtbl) == 0, "IExpandCollapseProvider.lpVtbl");
    _Static_assert(offsetof(IScrollProviderVtbl, QueryInterface) == 0, "IScrollProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IScrollProviderVtbl, AddRef) == 8, "IScrollProviderVtbl.AddRef");
    _Static_assert(offsetof(IScrollProviderVtbl, Release) == 16, "IScrollProviderVtbl.Release");
    _Static_assert(offsetof(IScrollProviderVtbl, Scroll) == 24, "IScrollProviderVtbl.Scroll");
    _Static_assert(offsetof(IScrollProviderVtbl, SetScrollPercent) == 32, "IScrollProviderVtbl.SetScrollPercent");
    _Static_assert(offsetof(IScrollProviderVtbl, get_HorizontalScrollPercent) == 40, "IScrollProviderVtbl.get_HorizontalScrollPercent");
    _Static_assert(offsetof(IScrollProviderVtbl, get_VerticalScrollPercent) == 48, "IScrollProviderVtbl.get_VerticalScrollPercent");
    _Static_assert(offsetof(IScrollProviderVtbl, get_HorizontalViewSize) == 56, "IScrollProviderVtbl.get_HorizontalViewSize");
    _Static_assert(offsetof(IScrollProviderVtbl, get_VerticalViewSize) == 64, "IScrollProviderVtbl.get_VerticalViewSize");
    _Static_assert(offsetof(IScrollProviderVtbl, get_HorizontallyScrollable) == 72, "IScrollProviderVtbl.get_HorizontallyScrollable");
    _Static_assert(offsetof(IScrollProviderVtbl, get_VerticallyScrollable) == 80, "IScrollProviderVtbl.get_VerticallyScrollable");
    _Static_assert(offsetof(IScrollProvider, lpVtbl) == 0, "IScrollProvider.lpVtbl");
    _Static_assert(offsetof(IScrollItemProviderVtbl, QueryInterface) == 0, "IScrollItemProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IScrollItemProviderVtbl, AddRef) == 8, "IScrollItemProviderVtbl.AddRef");
    _Static_assert(offsetof(IScrollItemProviderVtbl, Release) == 16, "IScrollItemProviderVtbl.Release");
    _Static_assert(offsetof(IScrollItemProviderVtbl, ScrollIntoView) == 24, "IScrollItemProviderVtbl.ScrollIntoView");
    _Static_assert(offsetof(IScrollItemProvider, lpVtbl) == 0, "IScrollItemProvider.lpVtbl");
    _Static_assert(offsetof(IGridProviderVtbl, QueryInterface) == 0, "IGridProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IGridProviderVtbl, AddRef) == 8, "IGridProviderVtbl.AddRef");
    _Static_assert(offsetof(IGridProviderVtbl, Release) == 16, "IGridProviderVtbl.Release");
    _Static_assert(offsetof(IGridProviderVtbl, GetItem) == 24, "IGridProviderVtbl.GetItem");
    _Static_assert(offsetof(IGridProviderVtbl, get_RowCount) == 32, "IGridProviderVtbl.get_RowCount");
    _Static_assert(offsetof(IGridProviderVtbl, get_ColumnCount) == 40, "IGridProviderVtbl.get_ColumnCount");
    _Static_assert(offsetof(IGridProvider, lpVtbl) == 0, "IGridProvider.lpVtbl");
    _Static_assert(offsetof(IGridItemProviderVtbl, QueryInterface) == 0, "IGridItemProviderVtbl.QueryInterface");
    _Static_assert(offsetof(IGridItemProviderVtbl, AddRef) == 8, "IGridItemProviderVtbl.AddRef");
    _Static_assert(offsetof(IGridItemProviderVtbl, Release) == 16, "IGridItemProviderVtbl.Release");
    _Static_assert(offsetof(IGridItemProviderVtbl, get_Row) == 24, "IGridItemProviderVtbl.get_Row");
    _Static_assert(offsetof(IGridItemProviderVtbl, get_Column) == 32, "IGridItemProviderVtbl.get_Column");
    _Static_assert(offsetof(IGridItemProviderVtbl, get_RowSpan) == 40, "IGridItemProviderVtbl.get_RowSpan");
    _Static_assert(offsetof(IGridItemProviderVtbl, get_ColumnSpan) == 48, "IGridItemProviderVtbl.get_ColumnSpan");
    _Static_assert(offsetof(IGridItemProviderVtbl, get_ContainingGrid) == 56, "IGridItemProviderVtbl.get_ContainingGrid");
    _Static_assert(offsetof(IGridItemProvider, lpVtbl) == 0, "IGridItemProvider.lpVtbl");
    _Static_assert(offsetof(ITableProviderVtbl, QueryInterface) == 0, "ITableProviderVtbl.QueryInterface");
    _Static_assert(offsetof(ITableProviderVtbl, AddRef) == 8, "ITableProviderVtbl.AddRef");
    _Static_assert(offsetof(ITableProviderVtbl, Release) == 16, "ITableProviderVtbl.Release");
    _Static_assert(offsetof(ITableProviderVtbl, GetRowHeaders) == 24, "ITableProviderVtbl.GetRowHeaders");
    _Static_assert(offsetof(ITableProviderVtbl, GetColumnHeaders) == 32, "ITableProviderVtbl.GetColumnHeaders");
    _Static_assert(offsetof(ITableProviderVtbl, get_RowOrColumnMajor) == 40, "ITableProviderVtbl.get_RowOrColumnMajor");
    _Static_assert(offsetof(ITableProvider, lpVtbl) == 0, "ITableProvider.lpVtbl");
    _Static_assert(offsetof(ITableItemProviderVtbl, QueryInterface) == 0, "ITableItemProviderVtbl.QueryInterface");
    _Static_assert(offsetof(ITableItemProviderVtbl, AddRef) == 8, "ITableItemProviderVtbl.AddRef");
    _Static_assert(offsetof(ITableItemProviderVtbl, Release) == 16, "ITableItemProviderVtbl.Release");
    _Static_assert(offsetof(ITableItemProviderVtbl, GetRowHeaderItems) == 24, "ITableItemProviderVtbl.GetRowHeaderItems");
    _Static_assert(offsetof(ITableItemProviderVtbl, GetColumnHeaderItems) == 32, "ITableItemProviderVtbl.GetColumnHeaderItems");
    _Static_assert(offsetof(ITableItemProvider, lpVtbl) == 0, "ITableItemProvider.lpVtbl");
    return 0;
}
