[Icon Theme]
Name=Test
Comment=A theme for the tests
Inherits=Parent
Directories=16x16/apps,32x32/apps,48x48/apps,scalable/apps
ScaledDirectories=32x32@2/apps

[16x16/apps]
Size=16
Type=Fixed

[32x32/apps]
Size=32
Type=Fixed

[32x32@2/apps]
Size=32
Scale=2
Type=Fixed

[48x48/apps]
Size=48
Type=Threshold
Threshold=4

[scalable/apps]
Size=48
MinSize=8
MaxSize=512
Type=Scalable

[Unlisted]
Size=40
Type=Fixed
